Custom agent repository documentation
DataDog/chef-datadog pull request #912
Opened 2024-03-25 13:15 UTC by Pythyu

### What does this PR do?

Details how to use `aptrepo` to use an agent from a different repository than default

### Motivation

### Additional Notes

### Possible Drawbacks / Trade-offs

### Describe how to test/QA your changes

### Reviewer's Checklist

2024-03-25 19:10 UTC, buraizu requested changes
Thanks, just requesting some minor edits per the documentation [style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md). Feel free to make additional changes if needed.

2024-03-25 19:10 UTC, buraizu commented on README.md
> +### Custom Agent Repository
```suggestion
### Custom Agent repository
```

2024-03-25 19:10 UTC, buraizu commented on README.md
> +Using staging repository
```suggestion
The example below uses the staging repository:

```

2024-03-26 15:45 UTC, buraizu approved these changes

2024-03-27 13:04 UTC, alopezz approved these changes

2024-03-28 16:49 UTC, merged